import type { ReactNode } from 'react';

export type HelpRole = 'admin' | 'leader';
export type HelpChapterId = 'pierwsze-kroki' | 'logowanie' | 'ekran-glowny' | 'rejestracja-czasu' | 'zmiany' | 'nieobecnosci' | 'kopiowanie-dnia' | 'baza-zlecen' | 'raport-hr' | 'raport-zlecen' | 'raport-nieobecnosci' | 'eksport' | 'kalendarz' | 'administracja' | 'faq';
export interface HelpScreenshotReference { id: string; alt: string; }
export interface HelpChapter { id: HelpChapterId; title: string; roles: HelpRole[]; content: ReactNode; screenshots: HelpScreenshotReference[]; }
const both: HelpRole[] = ['leader', 'admin'];
const shot = (id: string, alt: string): HelpScreenshotReference => ({ id, alt });

export const helpChapters: HelpChapter[] = [
  { id: 'pierwsze-kroki', title: 'Pierwsze kroki', roles: both, content: <><p>Warsztat służy do rejestrowania godzin przy zleceniach i nieobecności oraz do przygotowania raportów. Po zalogowaniu wybierz zadanie z menu.</p><p>Leader korzysta z Raportowania, Zleceń i Raportów. Administrator dodatkowo zarządza pracownikami, użytkownikami, słownikami, kalendarzem i importami oraz widzi pulpit.</p><p>Rozdziały z odznaką Administrator opisują czynności wymagające tej roli.</p></>, screenshots: [] },
  { id: 'logowanie', title: 'Logowanie', roles: both, content: <><p>Wpisz otrzymany login i hasło, a następnie wybierz <strong>Zaloguj się</strong>. Przełącznik motywu zmienia wygląd ekranu.</p><p>Po wygaśnięciu sesji albo aktualizacji aplikacji zaloguj się ponownie. Jeśli konto zostało dezaktywowane, skontaktuj się z administratorem.</p></>, screenshots: [shot('login-empty', 'Ekran logowania systemu Warsztat')] },
  { id: 'ekran-glowny', title: 'Ekran główny', roles: both, content: <><p>Menu boczne prowadzi do dostępnych ekranów. Leader widzi Raportowanie, Zlecenia, Raporty i Pomoc. Administrator widzi także Pulpit, Pracowników, Użytkowników, Słowniki, Kalendarz zakładowy i Importy.</p><h2>Pulpit administratora</h2><p>Pulpit pokazuje liczbę zleceń według statusu, godziny dzisiaj i w miesiącu oraz wykorzystanie planu godzin zleceń.</p></>, screenshots: [shot('nav-admin', 'Menu administratora'), shot('nav-leader', 'Menu lidera'), shot('dashboard', 'Pulpit administratora')] },
  { id: 'rejestracja-czasu', title: 'Rejestracja czasu pracy', roles: both, content: <><p>W Raportowaniu wybierz datę i pracownika. Strzałki zmieniają dzień, a „Dzisiaj” przywraca bieżącą datę. Skrót obok daty wskazuje dzień tygodnia.</p><ol><li>Wybierz rodzaj czasu. Zwykły dzień roboczy podpowiada G; zwykły weekend NS, jeśli ten kod istnieje. Dzień wolny może pozostawić wybór pusty.</li><li>Dla pracy wybierz zmianę I, II lub III i aktywne zlecenie, jeśli rodzaj czasu go wymaga.</li><li>Wpisz godziny i zapisz. Wyszukiwarki pracownika i zlecenia obsługują klawiaturę; Enter przeprowadza przez formularz.</li></ol><p>Przy przekroczeniu progów 8, 12 lub 24 godzin sprawdź ostrzeżenie i wybierz „Anuluj” albo „Ignoruj i zapisz”.</p></>, screenshots: [shot('reporting-filled', 'Wypełniony formularz czasu pracy'), shot('reporting-tablet', 'Raportowanie na tablecie'), shot('hours-warning', 'Ostrzeżenie dotyczące sumy godzin')] },
  { id: 'zmiany', title: 'Zmiany I / II / III', roles: both, content: <><p>Każdy nowy wpis pracy wymaga zmiany I, II albo III. Przełączenie rodzaju czasu na nieobecność czyści i blokuje pole „Zmiana”. Powrót do pracy wymaga ponownego wyboru.</p><p>Historyczne wpisy pracy bez zmiany są oznaczone „Brak danych”; przy ich edycji trzeba wybrać zmianę. Dla nieobecności raport pokazuje „Nie dotyczy”.</p></>, screenshots: [shot('absence-shift-disabled', 'Nieobecność z nieaktywnym polem zmiany')] },
  { id: 'nieobecnosci', title: 'Nieobecności', roles: both, content: <><p>Dla jednego dnia wybierz pracownika, datę, rodzaj oznaczony w słowniku jako nieobecność oraz godziny. Zmiana jest wyłączona.</p><h2>Zakres nieobecności</h2><p>Otwórz rejestrację zakresu, podaj daty i rodzaj, sprawdź podgląd dni, a następnie zapisz. Dni wolne wynikające z kalendarza nie są zapisywane jako robocze dni nieobecności.</p></>, screenshots: [shot('absence-range', 'Podgląd zakresu nieobecności')] },
  { id: 'kopiowanie-dnia', title: 'Kopiowanie poprzedniego dnia', roles: both, content: <><p>Po wybraniu pracownika i daty skopiuj strukturę wpisów z ostatniego dnia roboczego. Zmiany I, II i III pozostają przy wpisach pracy; nieobecności nie otrzymują zmiany.</p><p>Kopiowanie jest blokowane, gdy cel ma już wpisy, jest dniem wolnym albo źródłowy historyczny wpis pracy nie ma zmiany. Popraw źródło i ponów operację.</p></>, screenshots: [shot('copied-day-shifts', 'Lista wpisów z etykietami zmian po kopiowaniu')] },
  { id: 'baza-zlecen', title: 'Baza zleceń', roles: both, content: <><p>Wyszukuj po numerze, produkcie lub koncie księgowym. Filtr statusu i sortowanie zawężają widok. Leader może przeglądać i eksportować zlecenia; administrator może je dodawać i edytować.</p><p>Przy zamykaniu zlecenia podaj datę zakończenia. Historyczne zlecenia pozostają w raportach, lecz nie służą do nowych wpisów pracy.</p></>, screenshots: [shot('orders', 'Tabela zleceń i filtry')] },
  { id: 'raport-hr', title: 'Raport HR (wg pracowników)', roles: both, content: <><p>W Centrum Raportów otwórz „Godziny wg Pracowników”, ustaw miesiąc i wygeneruj raport. Tabela ma jedną kolumnę <strong>Zmiana</strong> oraz osobne wiersze dla I, II i III zmiany tego samego pracownika.</p><p>„Brak danych” oznacza historyczny wpis pracy bez zapisanej zmiany. „Nie dotyczy” obejmuje nieobecności, których godzin nie powiela się między zmianami. Sumy pozostają zgodne z ewidencją. Te same oznaczenia są w XLSX i CSV.</p></>, screenshots: [shot('hr-overview', 'Raport pracowników z kolumną Zmiana'), shot('hr-shifts', 'Wiersze I, II i III zmiany'), shot('hr-tablet', 'Raport HR na tablecie')] },
  { id: 'raport-zlecen', title: 'Raport wg zleceń', roles: both, content: <><p>Ustaw zakres i wygeneruj „Godziny wg Zleceń”. Godziny rzeczywiste dotyczą wybranego okresu, a odchylenie i procent realizacji uwzględniają postęp narastająco od daty zlecenia do końca okresu.</p><h2>Raport zamknięcia i kontrola</h2><p>Tryb zamknięcia uwzględnia zlecenia otwarte z godzinami i zamknięte w okresie. „Kontrola rozliczenia czasu” porównuje godziny zleceń i nieobecności z sumą godzin pracowników. Przy wyniku „Niezgodne” sprawdź różnicę i wpisy diagnostyczne.</p></>, screenshots: [shot('by-order', 'Raport godzin według zleceń'), shot('closure-control', 'Raport zamknięcia i sumy kontrolne')] },
  { id: 'raport-nieobecnosci', title: 'Raport nieobecności', roles: both, content: <><p>Wybierz „Okresy nieobecności”, ustaw zakres i wygeneruj raport. Kolejne dni robocze tej samej nieobecności tworzą okres. Weekend, święto lub firmowy dzień wolny może go łączyć bez zwiększania liczby dni roboczych.</p><p>Filtry zawężają wyniki, a stopka podaje łączną liczbę dni nieobecności.</p></>, screenshots: [shot('absence-periods', 'Raport okresów nieobecności i suma dni')] },
  { id: 'eksport', title: 'Eksport CSV/XLSX', roles: both, content: <><p>Po ustawieniu filtrów użyj przycisku eksportu XLSX lub CSV. Eksporty raportów zawierają nagłówki z zakresem i filtrami. Raport HR zachowuje pojedynczą kolumnę „Zmiana”, a raport zamknięcia wyniki kontroli.</p><p>Baza zleceń ma osobny eksport Excel bieżącego widoku. Plik zapisuje przeglądarka zgodnie z jej ustawieniami.</p></>, screenshots: [shot('export-actions', 'Przyciski eksportu raportu')] },
  { id: 'kalendarz', title: 'Kalendarz zakładowy', roles: ['admin'], content: <><p>Edycja wymaga roli Administrator. Wybierz zakres, sprawdź dni robocze i wolne, a dla wybranej daty zapisz wyjątek „Dzień roboczy” albo „Dzień wolny” z opcjonalnym opisem.</p><p>Wyjątek ma pierwszeństwo przed weekendem i świętem. Kalendarz wpływa na domyślny rodzaj czasu oraz dozwolone wpisy w dniu wolnym. Leader widzi skutek w formularzu, ale nie edytuje kalendarza.</p></>, screenshots: [shot('calendar', 'Kalendarz zakładowy z wyjątkiem')] },
  { id: 'administracja', title: 'Administracja', roles: ['admin'], content: <><p>Ten rozdział wymaga roli Administrator. W „Pracownikach” zarządzaj kartoteką i aktywnością; w „Użytkownikach” kontami i rolami. Samodzielna dezaktywacja konta lub odebranie sobie roli administratora jest blokowane.</p><h2>Słowniki</h2><p>Rodzaje czasu definiują kod, nazwę, wymóg zlecenia i oznaczenie nieobecności. Typy systemowe są chronione.</p><h2>Importy</h2><p>Pobierz szablon XLSX dla pracowników lub zleceń, wczytaj uzupełniony plik i sprawdź liczbę poprawnych oraz błędnych wierszy w historii.</p></>, screenshots: [shot('dictionaries', 'Słownik rodzajów czasu pracy'), shot('imports', 'Szablony i historia importów')] },
  { id: 'faq', title: 'Najczęstsze problemy / FAQ', roles: both, content: <><h2>Nie mogę zapisać pracy</h2><p>Wybierz zmianę I, II lub III oraz wymagane zlecenie. Przy edycji historycznego wpisu bez zmiany wybierz ją przed zapisem.</p><h2>Nie mogę skopiować dnia</h2><p>Cel może już mieć wpisy, być wolny albo źródło może zawierać pracę bez zmiany. Sprawdź komunikat i daty.</p><h2>Ostrzeżenie o godzinach</h2><p>Sprawdź sumę dnia przed „Ignoruj i zapisz”. Progi dotyczą 8 godzin pracy standardowej oraz 12 i 24 godzin łącznie.</p><h2>Poprzednie filtry w raporcie</h2><p>Każda zakładka pamięta filtry w bieżącej karcie przeglądarki. Użyj „Wyczyść filtry” lub zmień zakres.</p></>, screenshots: [] },
];

export const getHelpChapter = (id: string | null): HelpChapter => helpChapters.find((chapter) => chapter.id === id) ?? helpChapters[0];
export function helpChapterFromHash(hash: string): HelpChapterId | null {
  const id = hash.match(/^#help\/([^/]+)$/)?.[1];
  return helpChapters.find((chapter) => chapter.id === id)?.id ?? null;
}
